### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [IareDave/prj-rev-bwfs-dasmoto#6]
https://github.com/IareDave/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Crafts/resources/css/style.css#L9-L42

There's a lot of repetition in your CSS. Move shared styles into a more general selector so that those styles only need to be applied in one place:

```css
.brushes h1 {
  font-size: 32;
  font-weight: bold;
  color: white;
}
```

(By the way, these should be `h2` tags, not `h1`.)

You're also repeating the `font-family` style in a lot of these CSS rules, but you're missing that style in your `h3` and `p` selectors.

Consider applying this style in a more general selector, like `*`, so that you can just apply it to everything by default to be safe and write less code in the process.

```css
* {
  font-family: Helvetica;
}
```
